server:
  port: 8090

spring:
  main:
    web-application-type: servlet

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

